name: pipeline-scan 

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: mvn clean verify --f app/pom.xml
      - name: Review artifacts
        run: ls app
      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
         name: VeraWar
         path: app/target/verademo.war
  #Pipeline-Scan       
  Pipeline-Scan:
    needs: Build
    runs-on: ubuntu-latest
    env:
      SRCCLR_API_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mzc4NjUyLCJleHAiOjE2ODMyNzQwMTEsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJhZTVjMThjMi1iNjkyLTQ0ZjQtOTk5NS1jNGU4YmQxZjAyODgiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.tnH5x-TaYtvwZOv9OyjIFzJgUo0NvLLmdxElGSLqbf6-QKyN8z7ww3BesfWuWBCLtfv7Hpxz112ZNC5uPZD8OwMNEnCjV_nB5mPUGGihTEQs-0YpCHqSWNlyZSE91zdz2Hgo0__8WbbtYvSZ1o_DxqFdkUccbJ2iqYY_phX6OpA"
    steps:
      - name: Download war
        uses: actions/download-artifact@v2
        with:
          name: VeraWar
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - name: Change permissions
        run: chmod +x pipeline-scan.jar
      - name: Change permissions jar
        run: chmod +x verademo.war
        
# DESCARGAR POLITICA
      #- name: Download policy
      #  run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "eaed7dad0be43b4645b2d49a49d8d585" --veracode_api_key "c54ed47a8307a99ba7932860b11e5a2868246e1abbd00dd965ba4c431c8128f29755d4b99f43401683a45c8551b6b079fc68d3055eea5c68f1341c94241aa746" --request_policy "AppSec-A"

      - name: Review artifacts
        run: ls -a
      - name: Run Pipeline Scanner
      
#SIN POLITICA
       #run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "eaed7dad0be43b4645b2d49a49d8d585" --veracode_api_key "c54ed47a8307a99ba7932860b11e5a2868246e1abbd00dd965ba4c431c8128f29755d4b99f43401683a45c8551b6b079fc68d3055eea5c68f1341c94241aa746" --file "verademo.war" --fail_on_severity="Very High, High" --fail_on_cwe="95"
  
#CON POLITICA     
       #run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "eaed7dad0be43b4645b2d49a49d8d585" --veracode_api_key "c54ed47a8307a99ba7932860b11e5a2868246e1abbd00dd965ba4c431c8128f29755d4b99f43401683a45c8551b6b079fc68d3055eea5c68f1341c94241aa746" --file "verademo.war" --policy_file "AppSec-A.json"

#SIN VULNERABILIDADES
        run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "eaed7dad0be43b4645b2d49a49d8d585" --veracode_api_key "c54ed47a8307a99ba7932860b11e5a2868246e1abbd00dd965ba4c431c8128f29755d4b99f43401683a45c8551b6b079fc68d3055eea5c68f1341c94241aa746" --file "verademo.war" --fail_on_severity="Very Low"


#Analisis SCA 
  SCA-Scan:
    needs: Build
    runs-on: ubuntu-latest
    env:
      SRCCLR_API_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mzc4NjUyLCJleHAiOjE2ODMyNzQwMTEsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJhZTVjMThjMi1iNjkyLTQ0ZjQtOTk5NS1jNGU4YmQxZjAyODgiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.tnH5x-TaYtvwZOv9OyjIFzJgUo0NvLLmdxElGSLqbf6-QKyN8z7ww3BesfWuWBCLtfv7Hpxz112ZNC5uPZD8OwMNEnCjV_nB5mPUGGihTEQs-0YpCHqSWNlyZSE91zdz2Hgo0__8WbbtYvSZ1o_DxqFdkUccbJ2iqYY_phX6OpA"
    steps:
    - name: Download war
      uses: actions/download-artifact@v2
      with: 
        name: VeraWar
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Running SCA agent Based
      working-directory: app
      run: curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor 
  
  #Analisis Upload
  Upload-and-Scan:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download war
      uses: actions/download-artifact@v2
      with:
        name: VeraWar
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create folder
      run: mkdir app
    - name: Move artifact
      run: mv verademo.war app
    - name: Upload and scan
      uses: veracode/veracode-uploadandscan-action@master 
      with: 
        appname: 'AlejandraMUBA/verademo-1'
        createprofile: 'false'
        filepath: 'app'
        vid: "eaed7dad0be43b4645b2d49a49d8d585"
        vkey: "c54ed47a8307a99ba7932860b11e5a2868246e1abbd00dd965ba4c431c8128f29755d4b99f43401683a45c8551b6b079fc68d3055eea5c68f1341c94241aa746"
        scantimeout: 15
        exclude: '*.js'
        include: '*.war'
        criticality: 'VeryLow'
